# Generated by Django 3.2.8 on 2021-10-15 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_photo_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['updated'], 'verbose_name': '댓글', 'verbose_name_plural': '댓글'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-created'], 'verbose_name': '게시글', 'verbose_name_plural': '게시글'},
        ),
        migrations.AlterModelTable(
            name='comment',
            table='댓글',
        ),
        migrations.AlterModelTable(
            name='photo',
            table='게시글',
        ),
    ]
